### ISSUE TITLE
List of Site Additions

### ISSUE THREAD

**Issue by axelclark** [axelclark/ex338#522]
- [ ] Add Home Time Zone field to roster page.  This can just be a manual entry like the slack name
- [x] Add IR, Trades and Owners tabs to banner at top of page right now they are only accessible in drop down.  See #523 
- [x] lower down the list, but I think we need to be ready to add Total Draft Time for next year's draft.  each Team gets 30 hours (or whatever the number is) to use in the draft however they see fit.  once used, if they don't have a player in the queue, it opens for the next owner. See #639 
- [ ] way down the list:  could you add feature that allows an owner to enter estimated league points for sports that are still in process to see how standings are affected?
- [ ] it would be cool to have a "Trophy Room" or something like that on the owner's page or roster page that shows trophies (i could create) and records
- [x] I think you updated this last year, but can't recall for certain: during quite period of CBB and CHK, claims are emailed to the league, but player being claimed is hidden.  See #248 
- [x] Link fantasy teams from players page. See #524

**Comment by axelclark** [comment]
List of draft picks:  Should it list all or just new picks?

**Comment by axelclark** [comment]
- [x ] I think you updated this last year, but can't recall for certain: during quite period of CBB and CHK, claims are emailed to the league, but player being claimed is hidden.

See #248
